# KARMA CONFIGURATION FILE
#
# Add the config node 'karma.<GROUP>' in your
# permissions setup for the specified group for them to 
# be recognized as that group in karma
#
# Permissions:
# karma.gift: Give karma to another player (to stop people
#   with lots of alts to quickly gain karma)
# karma.promote.<GROUP>: Give a player enough karma
#   so that they are in that group (replaces /k builder)
# karma.set: Allow access to change the raw amount of
#   karma a player has (like to reward them with karma)
#

tracks:
    default:
        default: true
        recruit:
            color: d
            points: 0
        builder:
            color: '7'
            points: 10
        zonemaker:
            color: e
            points: 100
        zoneengineer:
            color: '6'
            points: 500
        zonemaster:
            color: a
            points: 1000
    moderation:
        minimod:
            color: b
            points: 500
        moderator:
            color: '9'
            points: 1000
        megamod:
            color: '1'
            points: 2000
    administration:
        caretaker:
            color: '2'
            points: 10000
        administrator:
            color: c
            points: 50000
party:
    time:
        # unit: minutes
        minimum: 10
        # unit: minutes
        maximum: 30
    points: 1
    silent: false
promotion:
    command: |
        manuadd <player> <group>
        mansave
demotion:
    command: |
        manuadd <player> <group>
        mansave
    demotetofirstgroup: false
gift:
    amounts:
        default: 1
        minimum: 1
        maximum: 1
    confirm:
        enabled: true
        # unit: seconds
        timeout: 60
    offline: false
    # unit: minutes
    cooldown: 60
war:
    bonus: true
    chance: 0.25
    points: 1
    messages:
        creator: Thanks for making warzones!
        player: Thanks for playing War!
import:
    bonus: true
    percent: 0.2
sqlite:
    database: karma.db
mysql:
    enabled: false
    host: localhost
    username: root
    password: 12345
    database: karma
afk:
    # unit: minutes
    time: 10
    triggers:
        chat: true
        command: true
        build: true
# Enabling move can drastically decrease server performance
        move: false
        damage: true