name: ${project.name}
version: ${project.version}
description: Karmic auto-ranking
author: tommytony
authors: [cmastudios]
website: https://github.com/taoneill/karma

main: com.tommytony.karma.KarmaPlugin

commands:
  karma:
    description: The main karma command
    usage: /<command> help
    aliases: k
permissions:
